"""
Student Management RAG Assistant — Streamlit app.

Upload PDF documents (handbooks, notices, circulars, records) in the
sidebar, build the knowledge base, then ask questions in the chat box.
Answers are generated by Llama 3 hosted on Groq, grounded only in the
documents you uploaded.

Run with:
    streamlit run app.py

Prereqs:
    A free Groq API key set as GROQ_API_KEY in Streamlit secrets
    (or as an environment variable when running locally).
"""

import os
import tempfile

import streamlit as st

from rag_core import (
    load_and_split_pdfs,
    build_vectorstore,
    load_vectorstore,
    build_rag_chain,
    answer_question,
    INDEX_DIR,
    OLLAMA_MODEL,
)

st.set_page_config(
    page_title="Student Management Assistant",
    page_icon="🎓",
    layout="centered",
    initial_sidebar_state="expanded",
)

# ---------------------------------------------------------------------
# Subtle / smooth theme — custom CSS
# ---------------------------------------------------------------------
st.markdown(
    """
    <style>
        /* ---------- global feel ---------- */
        html, body, [class*="css"] {
            font-family: "Inter", "Segoe UI", -apple-system, sans-serif;
        }

        * {
            transition: background-color 220ms ease, color 220ms ease,
                        border-color 220ms ease, box-shadow 220ms ease,
                        transform 180ms ease, opacity 220ms ease;
        }

        [data-testid="stAppViewContainer"] {
            background: linear-gradient(180deg, #fafbfc 0%, #f4f6f8 100%);
        }

        /* ---------- header ---------- */
        .app-header {
            padding: 0.25rem 0 1.25rem 0;
            border-bottom: 1px solid rgba(0,0,0,0.06);
            margin-bottom: 1.5rem;
            animation: fadeIn 500ms ease;
        }
        .app-header h1 {
            font-size: 1.65rem;
            font-weight: 650;
            color: #23272f;
            margin-bottom: 0.15rem;
            letter-spacing: -0.01em;
        }
        .app-header p {
            color: #7b8493;
            font-size: 0.92rem;
            margin: 0;
        }
        .status-pill {
            display: inline-flex;
            align-items: center;
            gap: 0.4rem;
            padding: 0.28rem 0.75rem;
            border-radius: 999px;
            font-size: 0.78rem;
            font-weight: 500;
            margin-top: 0.6rem;
        }
        .status-ready {
            background: #eafaf1;
            color: #1c8a5e;
            border: 1px solid #cdeee0;
        }
        .status-pending {
            background: #fff7ec;
            color: #b06a12;
            border: 1px solid #f3e2c4;
        }
        .status-dot {
            width: 6px; height: 6px; border-radius: 50%;
            background: currentColor;
        }

        /* ---------- sidebar ---------- */
        section[data-testid="stSidebar"] {
            background: #ffffff;
            border-right: 1px solid rgba(0,0,0,0.06);
        }
        section[data-testid="stSidebar"] .block-container {
            padding-top: 1.6rem;
        }
        section[data-testid="stSidebar"] h2 {
            font-size: 1.02rem;
            font-weight: 620;
            color: #2b2f38;
        }
        section[data-testid="stSidebar"] .stCaption, 
        section[data-testid="stSidebar"] p {
            color: #8a919e;
        }

        /* file uploader */
        [data-testid="stFileUploaderDropzone"] {
            background: #fafbfc;
            border: 1.5px dashed #d6dbe3 !important;
            border-radius: 12px;
        }
        [data-testid="stFileUploaderDropzone"]:hover {
            border-color: #b7c0cf !important;
            background: #f5f7fa;
        }

        /* buttons */
        .stButton > button {
            border-radius: 10px;
            border: 1px solid #e2e6ec;
            font-weight: 520;
            font-size: 0.88rem;
            padding: 0.5rem 0.9rem;
            box-shadow: none;
        }
        .stButton > button:hover {
            border-color: #c7ced9;
            box-shadow: 0 2px 10px rgba(20, 20, 30, 0.06);
            transform: translateY(-1px);
        }
        .stButton > button:active {
            transform: translateY(0);
        }
        .stButton > button[kind="primary"] {
            background: #2f3542;
            border: 1px solid #2f3542;
            color: #fff;
        }
        .stButton > button[kind="primary"]:hover {
            background: #21252f;
            border-color: #21252f;
            box-shadow: 0 4px 14px rgba(47, 53, 66, 0.25);
        }

        /* slider */
        [data-testid="stSlider"] label { color: #4d5460; font-size: 0.85rem; }

        /* divider */
        hr { border-color: rgba(0,0,0,0.06) !important; }

        /* ---------- chat area ---------- */
        [data-testid="stChatMessage"] {
            background: #ffffff;
            border: 1px solid rgba(0,0,0,0.05);
            border-radius: 14px;
            padding: 0.35rem 0.4rem;
            margin-bottom: 0.6rem;
            box-shadow: 0 1px 3px rgba(20,20,30,0.03);
            animation: fadeInUp 320ms ease;
        }

        [data-testid="stChatInput"] textarea {
            border-radius: 12px !important;
            border: 1px solid #e2e6ec !important;
            background: #ffffff;
        }
        [data-testid="stChatInput"] textarea:focus {
            border-color: #a9b2c2 !important;
            box-shadow: 0 0 0 3px rgba(90,110,150,0.08) !important;
        }

        /* expander (sources) */
        details {
            border-radius: 10px !important;
            border: 1px solid #eceff3 !important;
            background: #fbfcfd;
        }
        summary {
            font-size: 0.85rem !important;
            color: #5b6270 !important;
        }

        /* alerts */
        [data-testid="stAlert"] {
            border-radius: 10px;
            animation: fadeIn 300ms ease;
        }

        /* scrollbar */
        ::-webkit-scrollbar { width: 8px; height: 8px; }
        ::-webkit-scrollbar-thumb {
            background: #d8dce3;
            border-radius: 8px;
        }
        ::-webkit-scrollbar-thumb:hover { background: #c3c9d3; }

        @keyframes fadeIn {
            from { opacity: 0; }
            to { opacity: 1; }
        }
        @keyframes fadeInUp {
            from { opacity: 0; transform: translateY(6px); }
            to { opacity: 1; transform: translateY(0); }
        }
    </style>
    """,
    unsafe_allow_html=True,
)

# ---------------------------------------------------------------------
# Session state
# ---------------------------------------------------------------------
if "chain" not in st.session_state:
    st.session_state.chain = None
    st.session_state.retriever = None
if "messages" not in st.session_state:
    st.session_state.messages = []

# ---------------------------------------------------------------------
# Header
# ---------------------------------------------------------------------
ready = st.session_state.chain is not None
status_html = (
    '<span class="status-pill status-ready"><span class="status-dot"></span>Knowledge base ready</span>'
    if ready else
    '<span class="status-pill status-pending"><span class="status-dot"></span>No knowledge base loaded yet</span>'
)

st.markdown(
    f"""
    <div class="app-header">
        <h1>🎓 Student Management Assistant</h1>
        <p>Powered by Llama ({OLLAMA_MODEL} via Groq) — answers grounded in your documents</p>
        {status_html}
    </div>
    """,
    unsafe_allow_html=True,
)

# ---------------------------------------------------------------------
# Sidebar: build / load knowledge base
# ---------------------------------------------------------------------
with st.sidebar:
    st.header("📄 Knowledge Base")

    uploaded_files = st.file_uploader(
        "Upload student-related PDFs (handbooks, notices, etc.)",
        type=["pdf"],
        accept_multiple_files=True,
    )

    col1, col2 = st.columns(2)
    with col1:
        build_clicked = st.button("Build / Rebuild Index", type="primary", use_container_width=True)
    with col2:
        load_clicked = st.button("Load Saved Index", use_container_width=True)

    k = st.slider("Chunks to retrieve per question", 2, 8, 4)

    if build_clicked:
        if not uploaded_files:
            st.warning("Please upload at least one PDF first.")
        else:
            with st.spinner("Reading PDFs, chunking, and embedding..."):
                tmp_paths = []
                tmp_dir = tempfile.mkdtemp()
                for f in uploaded_files:
                    path = os.path.join(tmp_dir, f.name)
                    with open(path, "wb") as out:
                        out.write(f.getbuffer())
                    tmp_paths.append(path)

                chunks = load_and_split_pdfs(tmp_paths)
                vectorstore = build_vectorstore(chunks)
                try:
                    chain, retriever = build_rag_chain(vectorstore, k=k)
                    st.session_state.chain = chain
                    st.session_state.retriever = retriever
                except RuntimeError as e:
                    st.error(str(e))
                    st.stop()
            st.success(f"Index built from {len(uploaded_files)} file(s), {len(chunks)} chunks.")
            st.rerun()

    if load_clicked:
        if not os.path.exists(INDEX_DIR):
            st.warning("No saved index found yet. Build one first.")
        else:
            with st.spinner("Loading saved index..."):
                vectorstore = load_vectorstore()
                try:
                    chain, retriever = build_rag_chain(vectorstore, k=k)
                    st.session_state.chain = chain
                    st.session_state.retriever = retriever
                except RuntimeError as e:
                    st.error(str(e))
                    st.stop()
            st.success("Saved index loaded.")
            st.rerun()

    st.divider()
    st.caption(
        "Tip: rebuild the index whenever you add or change documents. "
        "The index is also saved to disk so you can reload it next time "
        "without re-uploading."
    )

# ---------------------------------------------------------------------
# Main: chat interface
# ---------------------------------------------------------------------
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

question = st.chat_input("Ask about student policies, deadlines, fees, rules...")

if question:
    if st.session_state.chain is None:
        st.error("Please build or load the knowledge base first (see sidebar).")
    else:
        st.session_state.messages.append({"role": "user", "content": question})
        with st.chat_message("user"):
            st.markdown(question)

        with st.chat_message("assistant"):
            with st.spinner("Thinking..."):
                answer, sources = answer_question(
                    st.session_state.chain, st.session_state.retriever, question
                )
                st.markdown(answer)

                with st.expander("📚 Sources used"):
                    for i, doc in enumerate(sources, 1):
                        st.markdown(
                            f"**{i}. {doc.metadata.get('source', 'unknown')}** "
                            f"(page {doc.metadata.get('page', '?')})"
                        )
                        st.caption(doc.page_content[:300] + "...")

        st.session_state.messages.append({"role": "assistant", "content": answer})
