"""
ClearLedger — Digital Banking RAG Assistant (Streamlit app).

Upload bank PDFs (terms & conditions, fee schedules, KYC policies,
product disclosures, account agreements) in the sidebar, build the
knowledge base, then ask questions in the chat box. Answers are
generated by Llama 3 hosted on Groq, grounded only in the documents
you uploaded.

This assistant answers POLICY and PRODUCT questions only — it does
not give personalized financial or investment advice, and it never
touches a live account.

Run with:
    streamlit run app_banking.py

Prereqs:
    A free Groq API key set as GROQ_API_KEY in Streamlit secrets
    (or as an environment variable when running locally).
"""

import os
import tempfile
from datetime import datetime

import streamlit as st

from rag_core import (
    load_and_split_pdfs,
    build_vectorstore,
    load_vectorstore,
    build_rag_chain,
    answer_question,
    INDEX_DIR,
    OLLAMA_MODEL,
)

st.set_page_config(
    page_title="ClearLedger",
    page_icon="🏦",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ---------------------------------------------------------------------
# Theme — "statement ledger": pale mint paper, hairline rules, tabular
# monospace figures, a geometric grotesk display face, deep-navy /
# emerald accents. Built to feel like a secure account statement
# rather than a chat toy.
# ---------------------------------------------------------------------
st.markdown(
    """
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@500;600;700&family=IBM+Plex+Mono:wght@400;500;600&display=swap" rel="stylesheet">

    <style>
        :root {
            --paper:    #f4f7f5;
            --panel:    #ffffff;
            --ink:      #10151f;
            --ink-soft: #5b6472;
            --line:     #dde3e1;
            --navy:     #12294f;
            --emerald:  #0f9960;
            --emerald-d:#0c7b4d;
            --amber:    #c98a2c;
        }

        html, body, [class*="css"] {
            font-family: "IBM Plex Mono", ui-monospace, monospace;
        }
        * {
            transition: background-color 200ms ease, border-color 200ms ease,
                        box-shadow 200ms ease, transform 160ms ease, opacity 200ms ease;
        }

        [data-testid="stAppViewContainer"] { background: var(--paper); }
        [data-testid="stHeader"] { background: transparent; }
        .block-container { padding-top: 2.2rem; max-width: 1140px; }

        /* ---------- hero / statement header ---------- */
        .hero-row {
            display: flex; justify-content: space-between; align-items: stretch;
            gap: 1.4rem; flex-wrap: wrap; margin-bottom: 1.7rem;
        }
        .hero-left { flex: 1 1 420px; }
        .eyebrow {
            display: inline-flex; align-items: center; gap: 0.45rem;
            font-size: 0.7rem; letter-spacing: 0.12em; font-weight: 600;
            color: var(--emerald-d); text-transform: uppercase;
            margin-bottom: 0.8rem;
        }
        .eyebrow .lock { font-size: 0.85rem; }
        .hero-title {
            font-family: "Space Grotesk", sans-serif;
            font-weight: 700;
            font-size: 2.5rem;
            line-height: 1.06;
            color: var(--navy);
            margin: 0 0 0.6rem 0;
            letter-spacing: -0.01em;
        }
        .hero-sub {
            font-size: 0.85rem; color: var(--ink-soft);
            max-width: 560px; line-height: 1.55; margin: 0 0 0.7rem 0;
        }
        .hero-note {
            display: inline-flex; align-items: center; gap: 0.35rem;
            font-size: 0.72rem; color: var(--ink-soft);
            border: 1px solid var(--line); background: var(--panel);
            border-radius: 6px; padding: 0.32rem 0.6rem;
        }

        .statement-card {
            flex: 0 0 300px;
            background: var(--panel);
            border: 1px solid var(--line);
            border-radius: 10px;
            padding: 1rem 1.15rem;
            box-shadow: 0 1px 2px rgba(16,21,31,0.04);
        }
        .statement-card .hdr {
            display: flex; justify-content: space-between; align-items: center;
            font-size: 0.68rem; letter-spacing: 0.08em; color: var(--ink-soft);
            text-transform: uppercase; margin-bottom: 0.6rem;
            border-bottom: 1px solid var(--line); padding-bottom: 0.5rem;
        }
        .statement-row {
            display: flex; justify-content: space-between; align-items: baseline;
            font-size: 0.82rem; padding: 0.32rem 0;
            border-bottom: 1px dashed var(--line);
        }
        .statement-row:last-child { border-bottom: none; }
        .statement-row .k { color: var(--ink-soft); }
        .statement-row .v { color: var(--ink); font-weight: 600; font-variant-numeric: tabular-nums; }
        .statement-row .v.accent { color: var(--emerald-d); }

        /* ---------- sidebar ---------- */
        section[data-testid="stSidebar"] {
            background: var(--panel);
            border-right: 1px solid var(--line);
        }
        section[data-testid="stSidebar"] .block-container { padding-top: 1.6rem; }
        section[data-testid="stSidebar"] h2, section[data-testid="stSidebar"] h3 {
            font-family: "Space Grotesk", sans-serif;
            font-weight: 700; color: var(--navy); font-size: 1.05rem;
        }
        section[data-testid="stSidebar"] p, section[data-testid="stSidebar"] label,
        section[data-testid="stSidebar"] .stCaption {
            color: var(--ink-soft) !important; font-size: 0.78rem !important;
        }

        .status-pill {
            display: inline-flex; align-items: center; gap: 0.5rem;
            background: var(--navy); color: #eef3f8;
            border-radius: 6px; padding: 0.42rem 0.8rem;
            font-size: 0.7rem; letter-spacing: 0.06em; font-weight: 600;
            text-transform: uppercase; margin-bottom: 1.2rem;
        }
        .status-pill .dot { width: 6px; height: 6px; border-radius: 50%; }
        .status-pill .dot.on  { background: var(--emerald); }
        .status-pill .dot.off { background: var(--amber); }

        .vault-box {
            border: 1px solid var(--line);
            background: var(--paper);
            border-radius: 8px;
            padding: 0.75rem 0.9rem;
            font-size: 0.78rem;
            color: var(--ink-soft);
            margin-bottom: 1.1rem;
        }
        .vault-box b { color: var(--ink); }
        .vault-box ul { margin: 0.35rem 0 0 1.1rem; padding: 0; }
        .vault-box li { margin-bottom: 0.15rem; }

        [data-testid="stFileUploaderDropzone"] {
            background: var(--paper);
            border: 1.5px dashed var(--line) !important;
            border-radius: 8px;
        }
        [data-testid="stFileUploaderDropzone"]:hover { border-color: var(--emerald) !important; }

        .stButton > button {
            border-radius: 6px;
            border: 1px solid var(--line);
            background: var(--panel);
            color: var(--ink);
            font-family: "IBM Plex Mono", monospace;
            font-weight: 500; font-size: 0.78rem;
            padding: 0.52rem 0.85rem;
        }
        .stButton > button:hover { border-color: var(--navy); transform: translateY(-1px); }
        .stButton > button[kind="primary"] {
            background: var(--emerald);
            border: 1px solid var(--emerald);
            color: #f2fbf6;
        }
        .stButton > button[kind="primary"]:hover {
            background: var(--emerald-d); border-color: var(--emerald-d);
            box-shadow: 0 4px 14px rgba(15,153,96,0.28);
        }

        hr { border-color: var(--line) !important; }

        /* ---------- empty state ---------- */
        .empty-card {
            border: 1px solid var(--line);
            background: var(--panel);
            border-radius: 12px;
            padding: 2.8rem 2rem;
            text-align: center;
            margin-bottom: 1.5rem;
        }
        .empty-icon {
            width: 50px; height: 50px; border-radius: 8px;
            background: var(--paper); border: 1px solid var(--line);
            display: flex; align-items: center; justify-content: center;
            font-size: 1.3rem; margin: 0 auto 1rem auto;
        }
        .empty-title {
            font-family: "Space Grotesk", sans-serif; font-weight: 700;
            font-size: 1.4rem; color: var(--navy); margin-bottom: 0.6rem;
        }
        .empty-body {
            font-size: 0.8rem; color: var(--ink-soft);
            max-width: 480px; margin: 0 auto 1.3rem auto; line-height: 1.6;
        }
        .step-pills { display: flex; justify-content: center; gap: 0.6rem; flex-wrap: wrap; }
        .step-pill {
            border: 1px solid var(--line); background: var(--paper);
            border-radius: 6px; padding: 0.4rem 0.85rem;
            font-size: 0.72rem; color: var(--ink-soft);
        }

        /* ---------- chat ---------- */
        [data-testid="stChatMessage"] {
            background: var(--panel);
            border: 1px solid var(--line);
            border-left: 3px solid var(--line);
            border-radius: 8px;
            padding: 0.3rem 0.4rem;
            margin-bottom: 0.55rem;
        }
        [data-testid="stChatInput"] textarea {
            border-radius: 8px !important;
            border: 1px solid var(--line) !important;
            background: var(--panel) !important;
            font-family: "IBM Plex Mono", monospace !important;
            color: var(--ink) !important;
        }
        [data-testid="stChatInput"] textarea:focus {
            border-color: var(--emerald) !important;
            box-shadow: 0 0 0 3px rgba(15,153,96,0.12) !important;
        }
        [data-testid="stChatInput"] button {
            background: var(--emerald) !important;
            border-radius: 6px !important;
        }

        details {
            border-radius: 8px !important;
            border: 1px solid var(--line) !important;
            background: var(--panel);
        }
        summary { font-size: 0.76rem !important; color: var(--ink-soft) !important; font-family: "IBM Plex Mono", monospace !important; }

        [data-testid="stAlert"] { border-radius: 8px; font-family: "IBM Plex Mono", monospace; font-size: 0.8rem; }

        ::-webkit-scrollbar { width: 8px; height: 8px; }
        ::-webkit-scrollbar-thumb { background: var(--line); border-radius: 8px; }
        ::-webkit-scrollbar-thumb:hover { background: #c7d0cd; }
    </style>
    """,
    unsafe_allow_html=True,
)

# ---------------------------------------------------------------------
# Session state
# ---------------------------------------------------------------------
if "chain" not in st.session_state:
    st.session_state.chain = None
    st.session_state.retriever = None
if "messages" not in st.session_state:
    st.session_state.messages = []
if "catalog_sources" not in st.session_state:
    st.session_state.catalog_sources = []
if "chunk_count" not in st.session_state:
    st.session_state.chunk_count = 0
if "indexed_at" not in st.session_state:
    st.session_state.indexed_at = None


def _register_index(vectorstore):
    """Pull catalog stats out of a built/loaded vector store for the UI."""
    docs = getattr(vectorstore, "documents", [])
    sources = sorted({d.metadata.get("source", "unknown") for d in docs})
    st.session_state.catalog_sources = sources
    st.session_state.chunk_count = len(docs)
    st.session_state.indexed_at = datetime.now().strftime("%b %d, %I:%M %p")


def _has_api_key() -> bool:
    key = st.secrets.get("GROQ_API_KEY", None) if hasattr(st, "secrets") else None
    return bool(key or os.environ.get("GROQ_API_KEY"))


# ---------------------------------------------------------------------
# Hero — headline + statement-style summary card
# ---------------------------------------------------------------------
doc_count = len(st.session_state.catalog_sources)

st.markdown(
    f"""
    <div class="hero-row">
        <div class="hero-left">
            <div class="eyebrow"><span class="lock">🔒</span>SECURE RETRIEVAL-AUGMENTED BANKING ASSISTANT</div>
            <div class="hero-title">Ask ClearLedger</div>
            <p class="hero-sub">Answers pulled straight from your bank's own terms, fee schedules,
            and product disclosures — chunked, ranked, and cited, not guessed. Powered by Llama
            ({OLLAMA_MODEL} via Groq).</p>
            <span class="hero-note">📄 Policy &amp; product info only — no live account access, no investment advice</span>
        </div>
        <div class="statement-card">
            <div class="hdr"><span>Index Summary</span><span>{"LIVE" if st.session_state.chain else "EMPTY"}</span></div>
            <div class="statement-row"><span class="k">Documents indexed</span><span class="v">{doc_count}</span></div>
            <div class="statement-row"><span class="k">Chunks embedded</span><span class="v">{st.session_state.chunk_count}</span></div>
            <div class="statement-row"><span class="k">Last updated</span><span class="v accent">{st.session_state.indexed_at or "—"}</span></div>
        </div>
    </div>
    """,
    unsafe_allow_html=True,
)

# ---------------------------------------------------------------------
# Sidebar: build / load knowledge base
# ---------------------------------------------------------------------
with st.sidebar:
    conn_ok = _has_api_key()
    dot_cls = "on" if conn_ok else "off"
    conn_text = "Connected via Groq" if conn_ok else "No API key set"
    st.markdown(
        f'<div class="status-pill"><span class="dot {dot_cls}"></span>{conn_text}</div>',
        unsafe_allow_html=True,
    )

    st.markdown("### Document Vault")

    if st.session_state.catalog_sources:
        items = "".join(f"<li>{s}</li>" for s in st.session_state.catalog_sources)
        st.markdown(
            f'<div class="vault-box"><b>Indexed now</b><ul>{items}</ul></div>',
            unsafe_allow_html=True,
        )
    else:
        st.markdown(
            '<div class="vault-box">Vault is empty — add a policy document below.</div>',
            unsafe_allow_html=True,
        )

    uploaded_files = st.file_uploader(
        "Upload bank PDFs — terms & conditions, fee schedules, KYC policy, "
        "product disclosures, account agreements",
        type=["pdf"],
        accept_multiple_files=True,
    )

    col1, col2 = st.columns(2)
    with col1:
        build_clicked = st.button("Build Index", type="primary", use_container_width=True)
    with col2:
        load_clicked = st.button("Load Saved", use_container_width=True)

    k = st.slider("Chunks to retrieve per question", 2, 8, 4)

    if build_clicked:
        if not uploaded_files:
            st.warning("Please upload at least one PDF first.")
        else:
            with st.spinner("Reading documents, chunking, and embedding..."):
                tmp_paths = []
                tmp_dir = tempfile.mkdtemp()
                for f in uploaded_files:
                    path = os.path.join(tmp_dir, f.name)
                    with open(path, "wb") as out:
                        out.write(f.getbuffer())
                    tmp_paths.append(path)

                chunks = load_and_split_pdfs(tmp_paths)
                vectorstore = build_vectorstore(chunks)
                try:
                    chain, retriever = build_rag_chain(vectorstore, k=k)
                    st.session_state.chain = chain
                    st.session_state.retriever = retriever
                    _register_index(vectorstore)
                except RuntimeError as e:
                    st.error(str(e))
                    st.stop()
            st.success(f"Index built from {len(uploaded_files)} file(s), {len(chunks)} chunks.")
            st.rerun()

    if load_clicked:
        if not os.path.exists(INDEX_DIR):
            st.warning("No saved index found yet. Build one first.")
        else:
            with st.spinner("Loading saved index..."):
                vectorstore = load_vectorstore()
                try:
                    chain, retriever = build_rag_chain(vectorstore, k=k)
                    st.session_state.chain = chain
                    st.session_state.retriever = retriever
                    _register_index(vectorstore)
                except RuntimeError as e:
                    st.error(str(e))
                    st.stop()
            st.success("Saved index loaded.")
            st.rerun()

    st.divider()
    st.caption(
        "Rebuild whenever policy documents change. The index is also saved to "
        "disk so you can reload it next time without re-uploading."
    )

# ---------------------------------------------------------------------
# Main: empty state or chat interface
# ---------------------------------------------------------------------
if st.session_state.chain is None and not st.session_state.messages:
    st.markdown(
        """
        <div class="empty-card">
            <div class="empty-icon">🏦</div>
            <div class="empty-title">Your vault is empty</div>
            <div class="empty-body">
                Add a terms &amp; conditions PDF, fee schedule, or KYC policy from the panel on
                the left and build the index — everything's chunked and embedded right here.
                Then ask a question below and get an answer grounded only in what you
                uploaded, with sources cited.
            </div>
            <div class="step-pills">
                <span class="step-pill">1 · upload a policy PDF</span>
                <span class="step-pill">2 · build the index</span>
                <span class="step-pill">3 · ask a question</span>
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

question = st.chat_input("Ask about fees, account terms, KYC, cards, transfers...")

if question:
    if st.session_state.chain is None:
        st.error("Please build or load the knowledge base first (see sidebar).")
    else:
        st.session_state.messages.append({"role": "user", "content": question})
        with st.chat_message("user"):
            st.markdown(question)

        with st.chat_message("assistant"):
            with st.spinner("Thinking..."):
                answer, sources = answer_question(
                    st.session_state.chain, st.session_state.retriever, question
                )
                st.markdown(answer)

                with st.expander("📄 Sources used"):
                    for i, doc in enumerate(sources, 1):
                        st.markdown(
                            f"**{i}. {doc.metadata.get('source', 'unknown')}** "
                            f"(page {doc.metadata.get('page', '?')})"
                        )
                        st.caption(doc.page_content[:300] + "...")

        st.session_state.messages.append({"role": "assistant", "content": answer})
