"""
Student Management RAG Assistant — Streamlit app.

Upload PDF documents (handbooks, notices, circulars, records) in the
sidebar, build the knowledge base, then ask questions in the chat box.
Answers are generated by Llama 3 hosted on Groq, grounded only in the
documents you uploaded.

Run with:
    streamlit run app.py

Prereqs:
    A free Groq API key set as GROQ_API_KEY in Streamlit secrets
    (or as an environment variable when running locally).
"""

import os
import tempfile
from datetime import datetime

import streamlit as st

from rag_core import (
    load_and_split_pdfs,
    build_vectorstore,
    load_vectorstore,
    build_rag_chain,
    answer_question,
    INDEX_DIR,
    OLLAMA_MODEL,
)

st.set_page_config(
    page_title="Ask the Registrar",
    page_icon="📖",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ---------------------------------------------------------------------
# Theme — warm archive / editorial: cream paper, italic serif display,
# uppercase monospace labels, terracotta accent.
# ---------------------------------------------------------------------
st.markdown(
    """
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Newsreader:ital,wght@0,400;0,500;1,400;1,500;1,600&family=IBM+Plex+Mono:wght@400;500;600&display=swap" rel="stylesheet">

    <style>
        :root {
            --paper:      #f3ecda;
            --paper-2:    #faf6ea;
            --ink:        #241f14;
            --ink-soft:   #5c5640;
            --olive:      #6a7a52;
            --line:       #e3d8b8;
            --rust:       #a8492f;
            --rust-dark:  #8f3c26;
            --navy:       #1c2331;
            --amber:      #c98a2c;
            --green:      #5f8a4f;
        }

        html, body, [class*="css"] {
            font-family: "IBM Plex Mono", ui-monospace, monospace;
        }
        * {
            transition: background-color 200ms ease, border-color 200ms ease,
                        box-shadow 200ms ease, transform 160ms ease, opacity 200ms ease;
        }

        [data-testid="stAppViewContainer"] {
            background: var(--paper);
        }
        [data-testid="stHeader"] { background: transparent; }
        .block-container { padding-top: 2.4rem; max-width: 1120px; }

        /* ---------- eyebrow + hero header ---------- */
        .eyebrow {
            display: flex; align-items: center; gap: 0.5rem;
            font-size: 0.72rem; letter-spacing: 0.14em; font-weight: 500;
            color: var(--olive); text-transform: uppercase;
            margin-bottom: 0.9rem;
        }
        .eyebrow .dot {
            width: 6px; height: 6px; border-radius: 50%;
            background: var(--green); display: inline-block;
        }
        .hero-title {
            font-family: "Newsreader", Georgia, serif;
            font-style: italic;
            font-weight: 500;
            font-size: 3rem;
            line-height: 1.08;
            color: var(--ink);
            margin: 0 0 0.7rem 0;
            letter-spacing: -0.01em;
        }
        .hero-sub {
            font-family: "IBM Plex Mono", monospace;
            font-size: 0.86rem;
            color: var(--ink-soft);
            max-width: 640px;
            line-height: 1.55;
            margin-bottom: 0;
        }
        .hero-row {
            display: flex; justify-content: space-between; align-items: flex-end;
            gap: 1.5rem; flex-wrap: wrap;
            border-bottom: 1px solid var(--line);
            padding-bottom: 1.6rem; margin-bottom: 1.8rem;
        }
        .stat-pill {
            font-size: 0.74rem; color: var(--ink-soft);
            border: 1px solid var(--line);
            background: var(--paper-2);
            border-radius: 8px;
            padding: 0.55rem 0.9rem;
            white-space: nowrap;
        }
        .stat-pill b { color: var(--rust); font-weight: 600; }

        /* ---------- sidebar ---------- */
        section[data-testid="stSidebar"] {
            background: var(--paper-2);
            border-right: 1px solid var(--line);
        }
        section[data-testid="stSidebar"] .block-container { padding-top: 1.6rem; }
        section[data-testid="stSidebar"] h3, 
        section[data-testid="stSidebar"] h2 {
            font-family: "Newsreader", Georgia, serif;
            font-style: italic;
            font-weight: 500;
            color: var(--ink);
            font-size: 1.2rem;
        }
        section[data-testid="stSidebar"] p, 
        section[data-testid="stSidebar"] .stCaption, 
        section[data-testid="stSidebar"] label {
            color: var(--ink-soft) !important;
            font-size: 0.8rem !important;
        }

        .conn-pill {
            display: inline-flex; align-items: center; gap: 0.5rem;
            background: var(--navy); color: #f2ede0;
            border-radius: 999px; padding: 0.45rem 0.9rem;
            font-size: 0.7rem; letter-spacing: 0.08em; font-weight: 600;
            text-transform: uppercase; margin-bottom: 1.3rem;
        }
        .conn-pill .dot { width: 6px; height: 6px; border-radius: 50%; }
        .conn-pill .dot.amber { background: var(--amber); }
        .conn-pill .dot.green { background: var(--green); }

        .catalog-box {
            border: 1px solid var(--line);
            background: var(--paper);
            border-radius: 10px;
            padding: 0.8rem 0.95rem;
            font-size: 0.8rem;
            color: var(--ink-soft);
            font-style: italic;
            font-family: "Newsreader", Georgia, serif;
            margin-bottom: 1.1rem;
        }
        .catalog-box ul { margin: 0.3rem 0 0 1.1rem; padding: 0; font-style: normal; font-family: "IBM Plex Mono", monospace; font-size: 0.76rem; }

        /* file uploader */
        [data-testid="stFileUploaderDropzone"] {
            background: var(--paper);
            border: 1.5px dashed var(--line) !important;
            border-radius: 10px;
        }
        [data-testid="stFileUploaderDropzone"]:hover {
            border-color: var(--rust) !important;
        }
        [data-testid="stFileUploader"] section small { color: var(--ink-soft); }

        /* buttons */
        .stButton > button {
            border-radius: 8px;
            border: 1px solid var(--line);
            background: var(--paper);
            color: var(--ink);
            font-family: "IBM Plex Mono", monospace;
            font-weight: 500;
            font-size: 0.8rem;
            padding: 0.55rem 0.9rem;
        }
        .stButton > button:hover {
            border-color: var(--ink-soft);
            transform: translateY(-1px);
        }
        .stButton > button[kind="primary"] {
            background: var(--rust);
            border: 1px solid var(--rust);
            color: #fbf3ea;
        }
        .stButton > button[kind="primary"]:hover {
            background: var(--rust-dark);
            border-color: var(--rust-dark);
            box-shadow: 0 4px 14px rgba(168, 73, 47, 0.28);
        }

        hr { border-color: var(--line) !important; }

        /* ---------- empty state hero card ---------- */
        .empty-card {
            border: 1px solid var(--line);
            background: var(--paper-2);
            border-radius: 16px;
            padding: 3.2rem 2rem;
            text-align: center;
            margin-bottom: 1.5rem;
        }
        .empty-icon {
            width: 52px; height: 52px; border-radius: 50%;
            background: var(--paper);
            border: 1px solid var(--line);
            display: flex; align-items: center; justify-content: center;
            font-size: 1.4rem;
            margin: 0 auto 1.1rem auto;
        }
        .empty-title {
            font-family: "Newsreader", Georgia, serif;
            font-style: italic; font-weight: 500;
            font-size: 1.6rem; color: var(--ink);
            margin-bottom: 0.7rem;
        }
        .empty-body {
            font-family: "IBM Plex Mono", monospace;
            font-size: 0.82rem; color: var(--ink-soft);
            max-width: 480px; margin: 0 auto 1.4rem auto;
            line-height: 1.6;
        }
        .step-pills { display: flex; justify-content: center; gap: 0.6rem; flex-wrap: wrap; }
        .step-pill {
            border: 1px solid var(--line);
            background: var(--paper);
            border-radius: 999px;
            padding: 0.45rem 0.9rem;
            font-size: 0.72rem;
            color: var(--ink-soft);
        }

        /* ---------- chat ---------- */
        [data-testid="stChatMessage"] {
            background: var(--paper-2);
            border: 1px solid var(--line);
            border-radius: 12px;
            padding: 0.3rem 0.4rem;
            margin-bottom: 0.6rem;
        }
        [data-testid="stChatInput"] textarea {
            border-radius: 10px !important;
            border: 1px solid var(--line) !important;
            background: var(--paper-2) !important;
            font-family: "IBM Plex Mono", monospace !important;
            color: var(--ink) !important;
        }
        [data-testid="stChatInput"] textarea:focus {
            border-color: var(--rust) !important;
            box-shadow: 0 0 0 3px rgba(168, 73, 47, 0.12) !important;
        }
        [data-testid="stChatInput"] button {
            background: var(--rust) !important;
            border-radius: 8px !important;
        }

        details {
            border-radius: 8px !important;
            border: 1px solid var(--line) !important;
            background: var(--paper-2);
        }
        summary { font-size: 0.78rem !important; color: var(--ink-soft) !important; font-family: "IBM Plex Mono", monospace !important; }

        [data-testid="stAlert"] { border-radius: 8px; font-family: "IBM Plex Mono", monospace; font-size: 0.82rem; }

        ::-webkit-scrollbar { width: 8px; height: 8px; }
        ::-webkit-scrollbar-thumb { background: var(--line); border-radius: 8px; }
        ::-webkit-scrollbar-thumb:hover { background: #cdbf94; }
    </style>
    """,
    unsafe_allow_html=True,
)

# ---------------------------------------------------------------------
# Session state
# ---------------------------------------------------------------------
if "chain" not in st.session_state:
    st.session_state.chain = None
    st.session_state.retriever = None
if "messages" not in st.session_state:
    st.session_state.messages = []
if "catalog_sources" not in st.session_state:
    st.session_state.catalog_sources = []
if "chunk_count" not in st.session_state:
    st.session_state.chunk_count = 0
if "indexed_at" not in st.session_state:
    st.session_state.indexed_at = None


def _register_index(vectorstore):
    """Pull catalog stats out of a built/loaded vector store for the UI."""
    docs = getattr(vectorstore, "documents", [])
    sources = sorted({d.metadata.get("source", "unknown") for d in docs})
    st.session_state.catalog_sources = sources
    st.session_state.chunk_count = len(docs)
    st.session_state.indexed_at = datetime.now().strftime("%b %d, %I:%M %p")


def _has_api_key() -> bool:
    key = st.secrets.get("GROQ_API_KEY", None) if hasattr(st, "secrets") else None
    return bool(key or os.environ.get("GROQ_API_KEY"))


# ---------------------------------------------------------------------
# Hero header
# ---------------------------------------------------------------------
doc_count = len(st.session_state.catalog_sources)
stat_html = (
    f'<div class="stat-pill">Indexed {st.session_state.indexed_at or "—"} · '
    f'<b>{st.session_state.chunk_count}</b> chunks across '
    f'<b>{doc_count}</b> document{"s" if doc_count != 1 else ""}</div>'
)

st.markdown(
    f"""
    <div class="hero-row">
        <div>
            <div class="eyebrow"><span class="dot"></span>RETRIEVAL-AUGMENTED STUDENT ASSISTANT · GROUNDED IN YOUR DOCUMENTS</div>
            <div class="hero-title">Ask the Registrar</div>
            <p class="hero-sub">Answers pulled straight from your school's own handbooks, notices, and
            circulars — chunked, ranked, and cited, not guessed. Upload a PDF in the panel on
            the left, build the index, then ask anything.</p>
        </div>
        {stat_html}
    </div>
    """,
    unsafe_allow_html=True,
)

# ---------------------------------------------------------------------
# Sidebar: build / load knowledge base
# ---------------------------------------------------------------------
with st.sidebar:
    conn_ok = _has_api_key()
    dot_cls = "green" if conn_ok else "amber"
    conn_text = "Connected via Groq" if conn_ok else "No API key — add GROQ_API_KEY"
    st.markdown(
        f'<div class="conn-pill"><span class="dot {dot_cls}"></span>{conn_text}</div>',
        unsafe_allow_html=True,
    )

    st.markdown("### *The Catalog*")
    if st.session_state.catalog_sources:
        items = "".join(f"<li>{s}</li>" for s in st.session_state.catalog_sources)
        st.markdown(
            f'<div class="catalog-box">What\'s indexed right now<ul>{items}</ul></div>',
            unsafe_allow_html=True,
        )
    else:
        st.markdown(
            '<div class="catalog-box">No documents indexed yet — add one below.</div>',
            unsafe_allow_html=True,
        )

    st.markdown("**Add your own documents**")
    st.caption("PDFs are read and chunked, then merged into the same search index.")

    uploaded_files = st.file_uploader(
        "Upload student-related PDFs (handbooks, notices, etc.)",
        type=["pdf"],
        accept_multiple_files=True,
        label_visibility="collapsed",
    )

    col1, col2 = st.columns(2)
    with col1:
        build_clicked = st.button("Build / Rebuild", type="primary", use_container_width=True)
    with col2:
        load_clicked = st.button("Load Saved", use_container_width=True)

    k = st.slider("Chunks to retrieve per question", 2, 8, 4)

    if build_clicked:
        if not uploaded_files:
            st.warning("Please upload at least one PDF first.")
        else:
            with st.spinner("Reading PDFs, chunking, and embedding..."):
                tmp_paths = []
                tmp_dir = tempfile.mkdtemp()
                for f in uploaded_files:
                    path = os.path.join(tmp_dir, f.name)
                    with open(path, "wb") as out:
                        out.write(f.getbuffer())
                    tmp_paths.append(path)

                chunks = load_and_split_pdfs(tmp_paths)
                vectorstore = build_vectorstore(chunks)
                try:
                    chain, retriever = build_rag_chain(vectorstore, k=k)
                    st.session_state.chain = chain
                    st.session_state.retriever = retriever
                    _register_index(vectorstore)
                except RuntimeError as e:
                    st.error(str(e))
                    st.stop()
            st.success(f"Index built from {len(uploaded_files)} file(s), {len(chunks)} chunks.")
            st.rerun()

    if load_clicked:
        if not os.path.exists(INDEX_DIR):
            st.warning("No saved index found yet. Build one first.")
        else:
            with st.spinner("Loading saved index..."):
                vectorstore = load_vectorstore()
                try:
                    chain, retriever = build_rag_chain(vectorstore, k=k)
                    st.session_state.chain = chain
                    st.session_state.retriever = retriever
                    _register_index(vectorstore)
                except RuntimeError as e:
                    st.error(str(e))
                    st.stop()
            st.success("Saved index loaded.")
            st.rerun()

    st.divider()
    st.caption(
        "Rebuild the index whenever you add or change documents. It's also saved "
        "to disk so you can reload it next time without re-uploading."
    )

# ---------------------------------------------------------------------
# Main: empty state or chat interface
# ---------------------------------------------------------------------
if st.session_state.chain is None and not st.session_state.messages:
    st.markdown(
        """
        <div class="empty-card">
            <div class="empty-icon">📖</div>
            <div class="empty-title">Ask the Registrar</div>
            <div class="empty-body">
                The index starts empty every time the app loads. Add a PDF from the panel
                on the left — handbook, notice, circular, fee schedule — and it's chunked
                and embedded right here. Then ask a question below and get an answer
                grounded only in what you uploaded, with sources cited.
            </div>
            <div class="step-pills">
                <span class="step-pill">1 · upload a document</span>
                <span class="step-pill">2 · build the index</span>
                <span class="step-pill">3 · ask a question</span>
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

question = st.chat_input("Ask about policies, deadlines, fees, rules...")

if question:
    if st.session_state.chain is None:
        st.error("Please build or load the knowledge base first (see sidebar).")
    else:
        st.session_state.messages.append({"role": "user", "content": question})
        with st.chat_message("user"):
            st.markdown(question)

        with st.chat_message("assistant"):
            with st.spinner("Thinking..."):
                answer, sources = answer_question(
                    st.session_state.chain, st.session_state.retriever, question
                )
                st.markdown(answer)

                with st.expander("📚 Sources used"):
                    for i, doc in enumerate(sources, 1):
                        st.markdown(
                            f"**{i}. {doc.metadata.get('source', 'unknown')}** "
                            f"(page {doc.metadata.get('page', '?')})"
                        )
                        st.caption(doc.page_content[:300] + "...")

        st.session_state.messages.append({"role": "assistant", "content": answer})
